import "./globals.css";
import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import Navigation from "@/components/navigation";
import classNames from "classnames";

const nunitoSans = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Radosław Rzepka",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="pl">


         <body
            className={classNames(
               nunitoSans.className,
               "grid justify-start bg-background px-7 pt-6 text-text lg:grid-cols-2",
            )}
         >
            <Navigation />
            <main>{children}</main>
         </body>
      </html>
   );
}
